name: CI Workflow

# Triggers the workflow on push or pull request to the main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    # The job runs on the latest Ubuntu
    runs-on: ubuntu-latest

    # Run the job in a container
    container:
      image: python:3.9-slim  # Use the Python 3.9 slim image

    # Services needed for the job (PostgreSQL in this case)
    services:
      postgres:
        image: postgres:alpine
        ports:
          - 5432:5432  # Mapping the PostgreSQL port
        env:
          POSTGRES_PASSWORD: pgs3cr3t
          POSTGRES_DB: testdb
        options: >-  # Health check options for the database service
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      # Checkout the code from the repository
      - name: Checkout
        uses: actions/checkout@v2

      # Set up Python dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel
          pip install -r requirements.txt
      
      # Add Linting
      - name: Lint with flake8
        run: |
          flake8 service --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 service --count --max-complexity=10 --max-line-length=127 --statistics

      # Run test
      - name: Run unit tests with nose
        run: nosetests
        env:
          DATABASE_URI: "postgresql://postgres:pgs3cr3t@postgres:5432/testdb"
            